# Generated by Django 3.2.6 on 2021-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
